### ISSUE TITLE
Error on thread select: 22

### ISSUE THREAD

**Issue by outoftime** [typhoeus/typhoeus#137]
We're seeing a very strange error when running a Typhoeus Hydra with a very large number of requests (on the order of magnitude of 10K).  Here's the relevant part of the backtrace:

```
RuntimeError
Error
error on thread select: 22 5356 -1 -1 -1
/u/apps/myapp/shared/bundle/ruby/1.9.1/gems/typhoeus-0.3.3.myapp.3/lib/typhoeus/multi.rb:21:in `multi_perform'
/u/apps/myapp/shared/bundle/ruby/1.9.1/gems/typhoeus-0.3.3.myapp.3/lib/typhoeus/multi.rb:21:in `perform'
/u/apps/myapp/shared/bundle/ruby/1.9.1/gems/typhoeus-0.3.3.myapp.3/lib/typhoeus/hydra.rb:95:in `run'
```

Note that I patched our install of Typhoeus to add extra information into the error message in an attempt to debug it:

``` c
rb_raise(rb_eRuntimeError, "error on thread select: %d %d %d %d %d", errno, maxfd, tv.tv_sec, tv.tv_usec, timeout);
```

The error 22 is an invalid argument error; per the [select man page](http://linux.die.net/man/2/select), this error condition indicates that "nfds is negative or the value contained within timeout is invalid." As we can see from the error output above, nfds looks fine, but both the original `timestamp`, the `tv.sec`, and the `tv.usec` are reporting as -1. This is pretty baffling since this should guarantee the `timestamp` is non-negative:

``` c
else if (timeout < 0) {
  timeout = 1;
}
```

And this should guarantee the `tv.usec` is non-negative:

``` c
tv.tv_usec = (timeout * 1000) % 1000000;
```

So I'm pretty much at a loss (unless the value of those variables somehow changes during the `rb_thread_select` call).

We're going to try working around this by batching up our data that we need to process with Typhoeus and thus limiting the number of requests that each Hydra needs to process, but it would still be great to figure out the underlying problem here. Thanks!

**Comment by magisterquis** [comment]
Apologies for strange terminology as I know nearly no Ruby.

Not to revive an ancient thread, but on OpenBSD, it seems the definition of Curl::Timeval didn't quite match up with OpenBSD's timeval.

Changing the definition in ethon/curls/classes.rb to match what OpenBSD is using under the hood seems to have done the trick.

**Comment by i0rek** [comment]
@magisterquis thanks for reporting. maybe providing a different definition for openbsd would help. I would totally merge a PR for something like that.

**Comment by dcws** [comment]
Likewise in FreeBSD, however the problem in FreeBSD's case (and I suspect openBSD's case) isn't typhoeus, but its libffi itself having the wrong definition for time_t and suseconds_t; I am posting a fix to them now, and I am commenting on all of these open bugs that I can so other people can find it more quickly than I did.

**Comment by i0rek** [comment]
Thank you @dcws

**Comment by slowbro** [comment]
Was this ever fixed? It looks like ethon still uses ffi 1.9.25, which doesn't have the patch for fixing things on FreeBSD.
