### ISSUE TITLE
Webmock compatibility is broken

### ISSUE THREAD

**Issue by challengee** [typhoeus/typhoeus#196]
Webmock chokes on the accessor `global_hooks` that is gone on `Hydra`.

stacktrace:

```
/Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/http_lib_adapters/typhoeus_hydra_adapter.rb:41:in `remove_after_request_callback': undefined method `global_hooks' for Typhoeus::Hydra:Class (NoMethodError)
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/http_lib_adapters/typhoeus_hydra_adapter.rb:23:in `disable!'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/webmock.rb:39:in `block in enable!'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/http_lib_adapters/http_lib_adapter_registry.rb:16:in `each'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/http_lib_adapters/http_lib_adapter_registry.rb:16:in `each_adapter'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/webmock.rb:38:in `enable!'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/webmock.rb:123:in `<module:WebMock>'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock/webmock.rb:1:in `<top (required)>'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock.rb:47:in `require'
    from /Users/mattias/.rvm/gems/ruby-1.9.3-p125/gems/webmock-1.8.7/lib/webmock.rb:47:in `<top (required)>'
```

**Comment by philsturgeon** [comment]
Using Webmock 2.3.2 and Typheous v1.3.0, they seem to work just fine via hydra or the shortcuts:

```
stub_request(:post, "http://fake/bar").to_return(body: '{"foo":"bar"}', headers: headers)
puts Typhoeus.post("http://fake/bar").body
"{\"foo\":\"bar\"}"
```
