### ISSUE TITLE
libcurl?

### ISSUE THREAD

**Issue by arjunmenon** [typhoeus/typhoeus#390]
bundle install was successful but `rails s` throws error that libcurl is not there
```
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ffi-1.9.3-x86-mingw32/lib/f
fi/library.rb:133:in `block in ffi_lib': Could not open library 'libcurl': The s
 (LoadError)ule could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be fou
nd.
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ffi-1.9.3-x86-
mingw32/lib/ffi/library.rb:100:in `map'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ffi-1.9.3-x86-
mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/li
b/ethon/curls/settings.rb:6:in `<module:Curl>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/li
b/ethon/curls/settings.rb:2:in `<module:Ethon>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/li
b/ethon/curls/settings.rb:1:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/li
b/ethon/curl.rb:27:in `<module:Curl>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/li
b/ethon/curl.rb:13:in `<module:Ethon>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/li
b/ethon/curl.rb:8:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/li
b/ethon.rb:11:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-
4.0.1/lib/active_support/dependencies.rb:229:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/typhoeus-0.6.9
/lib/typhoeus.rb:2:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bundler-1.6.2/
lib/bundler/runtime.rb:76:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bundler-1.6.2/
lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bundler-1.6.2/
lib/bundler/runtime.rb:72:in `each'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bundler-1.6.2/
lib/bundler/runtime.rb:72:in `block in require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bundler-1.6.2/
lib/bundler/runtime.rb:61:in `each'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bundler-1.6.2/
lib/bundler/runtime.rb:61:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bundler-1.6.2/
lib/bundler.rb:132:in `require'
        from D:/rails/api/api/config/application.rb:7:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/railties-4.0.1
/lib/rails/commands.rb:74:in `require'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/railties-4.0.1
/lib/rails/commands.rb:74:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/railties-4.0.1
/lib/rails/commands.rb:71:in `tap'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/railties-4.0.1
/lib/rails/commands.rb:71:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
I tried installing curl by unzipping in c:/windows dir, tried using this - http://www.confusedbycode.com/curl/
but it still does not work
I have windows 7

**Comment by bhameyie** [comment]
I encountered the same problem on Win 64 box. Resolving it for me was as simple as adding curl's bin folder to my "Path" environment variable.

**Comment by ShubhamGupta** [comment]
Installing `libcurl` fixes the issue. On Ubuntu:

`sudo apt-get install libcurl4-openssl-dev`

Hope it helps.

**Comment by danielfdickinson** [comment]
On Windows 10/11, if using RubyInstaller, you can add the path containing `libcurl.dll` to RUBY_DLL_PATH. (e.g. from an install of curl via some package manager).

Since normally `libcurl.dll` does no longer exist but is name `libcurl-x64.dll` on 65-bit systems, you will need to create a symbolic link (requires elevation).

E.g. in PowerShell `New-Item -ItemType SymbolicLink -Name libcurl.dll -Value <path\to\libcurl-x64.dll>`.

HTH
