### ISSUE TITLE
Stack too deep when before callback or cache for hydra is used.

### ISSUE THREAD

**Issue by simi** [typhoeus/typhoeus#408]
I'm facing this problem with latest (0.6.9) version:

``` ruby
# hydrocephalus.rb

require 'typhoeus'

hydra = Typhoeus::Hydra.new

urls = ["http://google.com"] * 6000

::Typhoeus.before do |request|
  request.finish(Typhoeus::Response.new) # simualting cache
end

requests = urls.map do |url|
  Typhoeus::Request.new(url).tap do |request|
    request.on_success do |response|
      # callback
    end
  end
end

requests.each {|req| hydra.queue(req)}
hydra.run
```

```
$ ruby hydrocephalus.rb 
/home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/request/cacheable.rb:5: stack level too deep (SystemStackError)
```

I think it is because `add` is called from `dequeue` method on `Typhoeus::Hydra` instance.

Better stacktrace (`raise "exception" if caller.length > 30` added before `request.finish` line):

```
[ryba@retro  prezo (master *#%)]❤ ruby hydrocephalus.rb 
hydrocephalus.rb:8:in `block in <main>': exception (RuntimeError)
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:21:in `call'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:21:in `block in add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `each'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/queueable.rb:63:in `dequeue'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:23:in `block in add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `each'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/queueable.rb:63:in `dequeue'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:23:in `block in add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `each'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/queueable.rb:63:in `dequeue'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:23:in `block in add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `each'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/queueable.rb:63:in `dequeue'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:23:in `block in add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `each'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/queueable.rb:63:in `dequeue'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:23:in `block in add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `each'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/queueable.rb:63:in `dequeue'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:23:in `block in add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `each'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/before.rb:20:in `add'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/queueable.rb:77:in `dequeue_many'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/runnable.rb:14:in `run'
        from /home/ryba/.rvm/gems/ruby-2.0.0-p481/gems/typhoeus-0.6.9/lib/typhoeus/hydra/memoizable.rb:51:in `run'
        from hydrocephalus.rb:21:in `<main>'
```

Is that real issue or am I just using hydra in bad way?

**Comment by erwanlr** [comment]
Any update on this one ?

I have a similar issue, but with on_complete:

```.rvm/gems/ruby-2.2.0/gems/typhoeus-0.7.1/lib/typhoeus/request.rb:204:in `map': stack level too deep (SystemStackError)```

I currently set the cache_ttl to 0 to avoid it when checking large number of URLs

**Comment by i0rek** [comment]
@erwanlr thanks for reporting. This is not an easy problem. I will take some time next week to look at it.

**Comment by erwanlr** [comment]
Thanks !

Yep, I know it's not an easy one, I tried to monkey patch things to get this fixed before posting but huuuuuuu :/

If it can help, the exception is raised around the 1840th requests (exactly the 1840th with the script given by @simi , and the 1837th in my real case scenario)

**Comment by erwanlr** [comment]
Also worth mentioning that if at least one request is not already cached and is done before the 1840th, the error will not appear.
In my case, I did 2k requests which were cached (persistent with a 10min TTL), then added a new url at the 1836th place, re-ran the check w/o any error, but then if run again (w/o any new URL, so they are all retrieved from the cache), the error was raised

**Comment by erwanlr** [comment]
Modified the original script to reproduce the behaviour I am talking in the post above:

```ruby
require 'typhoeus'

class Cache
  def initialize
    @memory = {}
  end

  def get(request)
    @memory[request]
  end

  def set(request, response)
    @memory[request] = response
  end
end

Typhoeus::Config.cache = Cache.new
@hydra = Typhoeus::Hydra.new

def run_hydra(urls)
  urls.each do |url|
    request = Typhoeus::Request.new(url)

    request.on_complete do |response|
      # p response.request.url
    end
    @hydra.queue(request)
  end

  @hydra.run
end

urls = 2000.times.map { |i| "http://google.com/#{i}" }

puts 'Populating Cache'

run_hydra(urls)

puts 'Cache Populated'

# Uncomment the line below to add an uncached request
# urls.insert(1830, 'http://uncached.com')

run_hydra(urls)
```

**Comment by erwanlr** [comment]
Yipeyeaaaaa, found a fix I think ^_^

Background: The problem is that the Hydra#add and Hydra#dequeue call each other when requests are cached, resulting in recursion and filling the caller until it can't handle anymore and blow up :o.

My fix is to remove calls to the Hydra#dequeue from Hydra#add and do the recursion in the Hydra#run until queued_requests is empty.

Script & Monkey Patching (tested with 2k and 50k requests):

```ruby
require 'typhoeus'

module Typhoeus
  class Hydra
    module Cacheable
      def add(request)
        if request.cacheable? && response = Typhoeus::Config.cache.get(request)
          response.cached = true
          request.finish(response)
        else
          super
        end
      end
    end

    module Memoizable
      def add(request)
        if request.memoizable? && response = memory[request]
          request.finish(response, true)
        else
          super
        end
      end
    end

    module Runnable
      def run
        dequeue_many
        multi.perform
        run unless queued_requests.empty?
      end
    end
  end
end

class Cache
  def initialize
    @memory = {}
  end

  def get(request)
    @memory[request]
  end

  def set(request, response)
    @memory[request] = response
  end
end

Typhoeus::Config.cache = Cache.new
@hydra = Typhoeus::Hydra.new

def run_hydra(urls)
  urls.each do |url|
    request = Typhoeus::Request.new(url)

    request.on_complete do |response|
      #p response.request.url
    end
    @hydra.queue(request)
  end

  @hydra.run
end

urls = 50000.times.map { |i| "http://google.com/#{i}" }

puts 'Populating Cache'

run_hydra(urls)

puts 'Cache Populated'

# Uncomment the line below to add an uncached request
# urls.insert(1830, 'http://uncached.com')

run_hydra(urls)
```

However, I have no idea if it will affect the performance :/, I will let you be the judge of that :P

**Comment by i0rek** [comment]
@erwanlr thanks for your work! Your solution changes the problem, but there is still recursion. I think I found another solution: https://github.com/typhoeus/typhoeus/commit/fc65a8ae02f1756b47af1ad95d37f2690f19ea66. `dequeue_many` won't trigger the recursion anymore. That should fix the problem since that should be the only place where it can run into stacklevertoodeep.

I also unrolled the magic even more. What do you think?

**Comment by erwanlr** [comment]
Yea that also do :). However, I have noticed a huge performance drop in the unroll branch (which is at 0.6.9) compared to the master. I first thought it was your fix but no :P

e.g: 20k requests with my fix in the master are done in 46s, whereas in the unroll (with either your fix or mine), it's performed in 5m30s.
With 2k requests it increases from 20s to 1m40s

**Comment by erwanlr** [comment]
Any ETA for the changes ?

**Comment by Ryan-Factual** [comment]
Apparently, this issue still is not fixed.
