### ISSUE TITLE
undefined method `mock=' while stubbing sequentially

### ISSUE THREAD

**Issue by Silox** [typhoeus/typhoeus#460]
Following the documentation for stubbing sequential responses, I get an `undefined method `mock=' for #<Array:0x007fe3cd604650>`. The following code reproduces the error:

```
irb(main):001:0> require 'typhoeus'
=> true
irb(main):002:0> response1 = Typhoeus::Response.new(code: 200, body: "{'name' : 'paul'}")
=> #<Typhoeus::Response:0x007fa0a3801380 @options={:code=>200, :body=>"{'name' : 'paul'}"}>
irb(main):003:0> response2 = Typhoeus::Response.new(code: 200, body: "{'name' : 'brad'}")
=> #<Typhoeus::Response:0x007fa0a0be23a8 @options={:code=>200, :body=>"{'name' : 'brad'}"}>
irb(main):004:0> Typhoeus.stub('www.example.com').and_return([response1, response2])
=> [[#<Typhoeus::Response:0x007fa0a3801380 @options={:code=>200, :body=>"{'name' : 'paul'}"}>, #<Typhoeus::Response:0x007fa0a0be23a8 @options={:code=>200, :body=>"{'name' : 'brad'}"}>]]
irb(main):005:0> Typhoeus.get('www.example.com') == response1
NoMethodError: undefined method `mock=' for #<Array:0x007fa0a1e30668>
        from /Users/silox/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/typhoeus-0.7.1/lib/typhoeus/expectation.rb:185:in `response'
        from /Users/silox/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/typhoeus-0.7.1/lib/typhoeus/expectation.rb:89:in `response_for'
        from /Users/silox/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/typhoeus-0.7.1/lib/typhoeus/request/stubbable.rb:20:in `run'
        from /Users/silox/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/typhoeus-0.7.1/lib/typhoeus/request/before.rb:26:in `run'
        from /Users/silox/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/typhoeus-0.7.1/lib/typhoeus/request/actions.rb:22:in `get'
        from (irb):5
        from /Users/silox/.rbenv/versions/2.2.0/bin/irb:11:in `<main>'
```

**Comment by i0rek** [comment]
@Silox thanks for the report! Are you using Typhoeus master? This feature has just been merged and is not released yet.

**Comment by Silox** [comment]
Ah, no, I'm on the latest version from Rubygems (0.7.1). I'll try again using the master branch.

**Comment by Silox** [comment]
The master branch indeed solves this issue, I should have tested that first, sorry!

**Comment by i0rek** [comment]
No worries, I am glad it works.

**Comment by Silox** [comment]
Is there an ETA for the next Rubygems release? I'd like to release an update for a gem with tests depending on the sequential stubbing code.

**Comment by i0rek** [comment]
I released a new version: https://rubygems.org/gems/typhoeus/versions/0.7.2 .

**Comment by Silox** [comment]
Awesome, thank you for the quick support!
