### ISSUE TITLE
Error when running ruby script

### ISSUE THREAD

**Issue by phxn** [typhoeus/typhoeus#500]
Hello, I'm getting the following error when I try to execute a script which uses Typhoeus, any idea what could be causing this or a possible fix?

/usr/local/lib/ruby/gems/2.2.0/gems/typhoeus-1.0.0/lib/typhoeus/easy_factory.rb:34:in `<class:EasyFactory>': uninitialized constant Typhoeus::EasyFactory::Set (NameError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/typhoeus-1.0.0/lib/typhoeus/easy_factory.rb:9:in `<module:Typhoeus>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/typhoeus-1.0.0/lib/typhoeus/easy_factory.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/typhoeus-1.0.0/lib/typhoeus.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from ./qobuz.rb:6:in `<main>'

Many thanks.

**Comment by phxn** [comment]
I'm guessing it has something to do with this: https://github.com/typhoeus/typhoeus/commit/3eadb16820cb0dcfbec164781fb8b14fd9e1ad35

I have managed to get it working by installing version 0.8.

**Comment by i0rek** [comment]
@phxn thanks for reporting! It is fixed and released in 1.0.1.
