### ISSUE TITLE
Typhoeus redirects forever if server returns a Location: redirect with a #url-fragment

### ISSUE THREAD

**Issue by jm3** [typhoeus/typhoeus#512]
### tumblr ))<>(( typhoeus redirect loop

In Typhoeus (with Faraday), this URL redirects forever back-and-forth to the server until the `FaradayMiddleware::FollowRedirects` limit is hit: **http://whathappensinadops.tumblr.com/post/48847516848/when-theres-something-on-the-io-that-we-dont-even**

### log:

```
: get http://whathappensinadops.tumblr.com/post/48847516848/when-theres-something-on-the-io-that-we-dont-even
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont-even%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
: get http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont%23_=_
Status: 301
ruby-2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:80:
in `block in perform_with_redirection': 
too many redirects; last one to: 
http://happensinadops.com/post/48847516848/when-theres-something-on-the-io-that-we-dont#_=_ 
(FaradayMiddleware::RedirectLimitReached)

 ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:65:in `call'
 ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:65:in `block in finish'
 ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:65:in `each'
 ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:65:in `finish'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:100:in `block in request'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/request/callbacks.rb:128:in `call'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/request/callbacks.rb:127:in `each'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/request/operations.rb:35:in `finish'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/easy_factory.rb:129:in `block in set_callback'
 ruby-2.2.3/gems/ethon-0.8.0/lib/ethon/easy/response_callbacks.rb:65:in `call'
 ruby-2.2.3/gems/ethon-0.8.0/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
 ruby-2.2.3/gems/ethon-0.8.0/lib/ethon/easy/response_callbacks.rb:65:in `each'
 ruby-2.2.3/gems/ethon-0.8.0/lib/ethon/easy/response_callbacks.rb:65:in `complete'
 ruby-2.2.3/gems/ethon-0.8.0/lib/ethon/multi/operations.rb:151:in `check'
 ruby-2.2.3/gems/ethon-0.8.0/lib/ethon/multi/operations.rb:164:in `run'
 ruby-2.2.3/gems/ethon-0.8.0/lib/ethon/multi/operations.rb:43:in `perform'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/hydra/runnable.rb:15:in `run'
 ruby-2.2.3/gems/typhoeus-0.8.0/lib/typhoeus/hydra/memoizable.rb:51:in `run'
 ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:278:in `in_parallel'
 ./fragment-redirect-overflow.rb:15:in `<main>'
```

**Note** that the trailing `#url-fragment` is added by the server in the [first] Location redirect (as a url-encoded %23), it's not in the original url, so this is at least partly a Tumblr bug. That said, it works fine in both `curl` and Chrome with after following a single Location: redirect, not 50, so I would sort of expect Typhoeus to behave a little more like that.

Should Typhoeus be url-decoding the %23 and then discarding the #fragment?

### test case:

https://gist.github.com/jm3/14469eb935dc8974f531

**Comment by jm3** [comment]
This is also reproducible with another tumblr URL: http://mtvinsights.tumblr.com/post/32884529556/50-shades-of-nerd; seems to be what happens when a tumblr user renames their blog — Tumblr serves a `301` redirect response with a trailing `#_=_` that sends Typhoeus / Faraday into an infinite loop.

**Comment by felipedmesquita** [comment]
@jm3 can you confirm this is still an issue for the latest version?

**Comment by felipedmesquita** [comment]
Closing to clean things up. Please don't hesitate to open new issues on problems affecting current versions.

**Comment by jm3** [comment]
@felipedmesquita thank you for the follow-up :) I appreciate the attention to this issue.
