### ISSUE TITLE
Multipart post (body params with file) fails

### ISSUE THREAD

**Issue by mikeys** [typhoeus/typhoeus#542]
It seems like that when trying to post combined data (using `multipart/formdata`) of simple params and a file, each param must be converted to a string first. Otherwise, an error is raised as can be seen below:

```
response = Typhoeus.post('http://localhost/api', body: { param1: 50, param2: 50, file: file }) 
# raises "NoMethodError: undefined method `bytesize' for 50:Fixnum"

response = Typhoeus.post('http://localhost/api', body: { param1: '50', param2: '50', file: file }
# No Error - The params are specified as plain strings

response = Typhoeus.post('http://localhost/api', body: { param1: 50, param2: 50 })
# No Error - Perhaps related to `Content-Type: application/x-www-form-urlencoded` which has a different behaviour  inside Typhoeus
```

Am I missing something? Is this by design? (RestClient equivalent is pretty straightforward: `RestClient.post('http://localhost:9090/api', file: file, param1: 50, param2: 50)`)

**Comment by jonaldomo** [comment]
I dug into this a bit, not sure helpful this is going to be...  My brain hurts, I need some direction from someone more experienced on the project.

Here is the stacktrace:

```
NoMethodError:
       undefined method `bytesize' for 1:Fixnum
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/form.rb:86:in "form_add"
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/form.rb:65:in "block in materialize"
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/form.rb:65:in "each"
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/form.rb:65:in "materialize"
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/http/postable.rb:22:in "set_form"
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/http/actionable.rb:101:in "setup"
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/http/post.rb:16:in "setup"
/Users/jonaldomo/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon/easy/http.rb:39:in "http_request"
./lib/typhoeus/easy_factory.rb:81:in "get"
./lib/typhoeus/request/operations.rb:15:in "run"
./lib/typhoeus/request/cacheable.rb:18:in "run"
./lib/typhoeus/request/block_connection.rb:31:in "run"
./lib/typhoeus/request/stubbable.rb:25:in "run"
./lib/typhoeus/request/before.rb:26:in "run"
./lib/typhoeus/request/actions.rb:38:in "post"
```

And the block of code throwing the error:

```
if form.multipart?
  form.escape = false
  form.materialize
  easy.httppost = form.first.read_pointer
else
  form.escape = easy.escape?
  easy.postfieldsize = form.to_s.bytesize
  easy.copypostfields = form.to_s
end
```

```
      def materialize
        query_pairs.each { |pair| form_add(pair.first.to_s, pair.last) }
      end
```

```
      def form_add(name, content)
        case content
        when Array
          Curl.formadd(first, last,
                       :form_option, :copyname, :pointer, name,
                       :form_option, :namelength, :long, name.bytesize,
                       :form_option, :file, :string, content[2],
                       :form_option, :filename, :string, content[0],
                       :form_option, :contenttype, :string, content[1],
                       :form_option, :end
                      )
        else
          Curl.formadd(first, last,
                       :form_option, :copyname, :pointer, name,
                       :form_option, :namelength, :long, name.bytesize,
                       :form_option, :copycontents, :pointer, content,
                       :form_option, :contentslength, :long, content ? content.bytesize : 0,
                       :form_option, :end
                      )
        end
```

As far as RestClient handling it properly.  Typhoeus is a wrapper around libcurl.  RestClient is a wrapper of Net::HTTP in Ruby so the end request is different code around the same standard.

**Comment by jonaldomo** [comment]
Ok, I got a walk in to clear my head.  This is works:
```
Curl.formadd(first, last,
                       :form_option, :copyname, :pointer, name,
                       :form_option, :namelength, :long, name.bytesize,
                       :form_option, :copycontents, :pointer, content.to_s,
                       :form_option, :contentslength, :long, content ? content.to_s.bytesize : 0,
                       :form_option, :end
                      )
```
Submitting PR to ethon repo now...
