### ISSUE TITLE
The Ethon depedency is not thread safe, can you put a warning in the readme?

### ISSUE THREAD

**Issue by samuelpismel** [typhoeus/typhoeus#548]
See https://github.com/typhoeus/ethon/issues/131

**Comment by i0rek** [comment]
https://github.com/typhoeus/ethon/issues/131#issuecomment-263145038

**Comment by aramisbear** [comment]
We just experienced this issue after upgrading to Typhoeus 1.3.0. We had to downgrade back to 1.1.2. Our code that called APIs with Typhoeus started failing constantly when run within Sidekiq background jobs ONLY. From a Rails console it was fine. Within Unicorn it was fine. Within a Sidekiq job it was a consistent failure.

**Comment by i0rek** [comment]
The issues is fairly generic. And while it is true that it is not entirely threadsafe, you should not have issues like the one you described @aramisbear. Could you provide more details?

**Comment by aramisbear** [comment]
Where we saw the issue, multiple threads were calling the same API's and the conflicting calls were resulting in this error message: `IOError: closed stream`

Here is the stack trace, mildly obfuscated.

```

"/home/code/.rvm/gems/ruby-2.3.4@code/gems/ethon-0.10.1/lib/ethon/easy/callbacks.rb:70:in `write'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/ethon-0.10.1/lib/ethon/easy/callbacks.rb:70:in `print'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/ethon-0.10.1/lib/ethon/easy/callbacks.rb:70:in `block in debug_callback'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/ethon-0.10.1/lib/ethon/easy/operations.rb:29:in `easy_perform'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/ethon-0.10.1/lib/ethon/easy/operations.rb:29:in `perform'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/typhoeus-1.3.0/lib/typhoeus/request/operations.rb:16:in `run'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/typhoeus-1.3.0/lib/typhoeus/request/cacheable.rb:18:in `run'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/typhoeus-1.3.0/lib/typhoeus/request/block_connection.rb:31:in `run'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/typhoeus-1.3.0/lib/typhoeus/request/stubbable.rb:25:in `run'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/typhoeus-1.3.0/lib/typhoeus/request/before.rb:26:in `run'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/auth-sdk-ruby-1.3.6/lib/auth-sdk-ruby/rest.rb:81:in `request'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/auth-sdk-ruby-1.3.6/lib/auth-sdk-ruby/rest.rb:63:in `block (2 levels) in <module:Rest>'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/auth-sdk-ruby-1.3.6/lib/auth-sdk-ruby.rb:63:in `create_application_token'"
 "/home/code/code/app/workers/notification_creator.rb:6:in `api_verification'"
 "/home/code/code/app/workers/notification_creator.rb:62:in `initialize_job'"
 "/home/code/code/app/workers/notification_creator.rb:27:in `perform'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:155:in `execute_job'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:136:in `block (3 levels) in process'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/request_store-sidekiq-0.1.0/lib/request_store/sidekiq/server_middleware.rb:5:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:368:in `perform_action_with_newrelic_trace'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-unique-jobs-5.0.9/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/middleware.rb:9:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/logging.rb:32:in `with_context'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:131:in `block (2 levels) in process'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:171:in `stats'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:130:in `block in process'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/rails.rb:47:in `block in call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/activesupport-5.0.2/lib/active_support/reloader.rb:68:in `block in wrap'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/activesupport-5.0.2/lib/active_support/reloader.rb:67:in `wrap'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/rails.rb:46:in `call'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:122:in `process'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:81:in `process_one'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:69:in `run'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:17:in `watchdog'"
 "/home/code/.rvm/gems/ruby-2.3.4@code/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:25:in `block in safe_thread'"
```

**Comment by i0rek** [comment]
@aramisbear are you using the `verbose: true` option? Can you show me how you are using Typhoeus?

**Comment by tilo** [comment]
I see rails 5.0.6, sidekiq 5.0.5 and typhoeus 1.3.0 having isssues without verbose

**Comment by i0rek** [comment]
@tilo can you show me what exactly you are doing and what exactly your issue is?
