### ISSUE TITLE
libcurl error on Ubuntu Linux version 18.04.1 LTS

### ISSUE THREAD

**Issue by muescha** [typhoeus/typhoeus#627]
dreamhost upgrade my server to `Ubuntu Linux version 18.04.1 LTS` and now i get this error:

```
.../vendor/bundle/ruby/1.9.1/gems/ffi-1.9.3/lib/ffi/library.rb:263:in `attach': unhandled exception                   
        from .../vendor/bundle/ruby/1.9.1/gems/ffi-1.9.3/lib/ffi/library.rb:263:in `attach_function'                  
        from .../vendor/bundle/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/libc.rb:16:in `<module:Libc>'                    
        from .../vendor/bundle/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/libc.rb:6:in `<module:Ethon>'                    
        from .../vendor/bundle/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/libc.rb:1:in `<top (required)>'                  
        from .../vendor/bundle/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon.rb:10:in `require'                               
        from .../vendor/bundle/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon.rb:10:in `<top (required)>'                      
        from .../vendor/bundle/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus.rb:2:in `require'                          
        from .../vendor/bundle/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus.rb:2:in `<top (required)>'                 
        from .../app/main.rb:4:in `require'                                                                           
        from .../app/main.rb:4:in `<top (required)>'                                                                  
        from config.ru:61:in `require'                                                                                                                                  
        from config.ru:61:in `block in <main>'                                                                                                                          
        from .../vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'                   
        from .../vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'                      
        from config.ru:in `new'                                                                                                                                         
        from config.ru:in `<main>'                                                                                                                                      
        from .../vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'                            
        from .../vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'                 
        from .../vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'                      
        from ./dispatch_fcgi.rb:21:in `<main>'      
```
(replaced my folder with `...`)

check installed versions:
```
$ dpkg -l | grep libcurl                                                                                                
ii  libcurl3-gnutls:amd64                       7.58.0-2ubuntu3.7                           amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)  
ii  libcurl4:amd64                              7.58.0-2ubuntu3.7                           amd64        easy-to-use client-side URL transfer library (OpenSSL flavour) 
ii  libcurl4-gnutls-dev:amd64                   7.58.0-2ubuntu3.7                           amd64        development files and documentation for libcurl (GnuTLS flavour
)                                                                                                                                                                       
ii  libwww-curl-perl                            4.17-4build1                                amd64        Perl bindings to libcurl                                       
ii  python-pycurl                               7.43.0.1-0.2                                amd64        Python bindings to libcurl
```

i know the version is very behind the current releases - but since it is a small legacy app i try to avoid to upgrade the gems :(

**Comment by muescha** [comment]
still an issue also after upgrading ruby & gems ... someone an idea how to fix this?


i get this error on startup while `require 'typhoeus'`:

```bash
/.../vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach': unhandled exception
        from /.../vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach_function'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:16:in `<module:Libc>'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:6:in `<module:Ethon>'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:1:in `<top (required)>'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:14:in `require'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:14:in `<top (required)>'
        from /.../vendor/bundle/ruby/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `require'
        from /.../vendor/bundle/ruby/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
        from /.../app/main.rb:4:in `require'
        from /.../app/main.rb:4:in `<top (required)>'
        from config.ru:61:in `require'
        from config.ru:61:in `block in <main>'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
        from ./dispatch_fcgi.rb:21:in `<main>'
```

(replaced my folder with `...`)


check installed version:

```
dpkg -l | grep libcurl 
ii libcurl3-gnutls:amd64 7.58.0-2ubuntu3.8 amd64 easy-to-use client-side URL transfer library (GnuTLS flavour) 
ii libcurl4:amd64 7.58.0-2ubuntu3.8 amd64 easy-to-use client-side URL transfer library (OpenSSL flavour) 
ii libcurl4-gnutls-dev:amd64 7.58.0-2ubuntu3.8 amd64 development files and documentation for libcurl (GnuTLS flavour) 
ii libwww-curl-perl 4.17-4build1 amd64 Perl bindings to libcurl 
ii python-pycurl 7.43.0.1-0.2 amd64 Python bindings to libcurl 
ii ruby-curb 0.9.4-1build2 amd64 Ruby libcurl bindings 
```

**Comment by PericlesTheo** [comment]
Hey @muescha,

Can you see if the code below runs in your box?

```ruby
module MyLib
  extend FFI::Library
  ffi_lib 'c'
  attach_function :getdtablesize, [], :int
end

MyLib.getdtablesize
```

**Comment by PericlesTheo** [comment]
Conversation followed here: https://github.com/ffi/ffi/issues/718

Closing for now as this seems to be an FFI issue along with the host OS.

**Comment by PericlesTheo** [comment]
How about our friends over at [Faraday](https://github.com/lostisland/faraday)?

**Comment by muescha** [comment]
thx i will if it supports parallel requests

**Comment by muescha** [comment]
i have done this:

```ruby
hydra = Typhoeus::Hydra.new(:max_concurrency => 5)
cookies = $agent.cookies.join('; ')
users.each do|user_id|
  url = get_url(user_id)
  req = Typhoeus::Request.new(url , headers: {'Cookie' => cookies} )
  req.on_complete do |response|
    online_code = 'err'
    if response.success?
      online_code = response.body
    end
    online[user_id] = online_code
  end
  hydra.queue req
end
hydra.run
```

**Comment by muescha** [comment]
is there a way to say `Typhoeus` not to load `ethon` when i do a `require 'typhoeus'`?
