### ISSUE TITLE
Verbose throws Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by sdhull** [typhoeus/typhoeus#657]
I'm working on a tool that is to be used by external developers, and want to enable verbose debugging for typhoeus as some people have reported mysterious errors.

The tool works fine for me, however when I set `Typhoeus::Config.verbose = true`, it fails with

```
ALPN, offering h2
ALPN, offering http/1.1
successfully set certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
TLSv1.2 (OUT), TLS handshake, Client hello (1):
/Users/stevenhull/.gem/ruby/2.4.9/gems/ethon-0.12.0/lib/ethon/easy/callbacks.rb:70:in `write': "\xE3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /Users/stevenhull/.gem/ruby/2.4.9/gems/ethon-0.12.0/lib/ethon/easy/callbacks.rb:70:in `print'
	from /Users/stevenhull/.gem/ruby/2.4.9/gems/ethon-0.12.0/lib/ethon/easy/callbacks.rb:70:in `block in debug_callback'
```

I want to allow users to set `verbose = true` to aid in debugging issues in other environments, but simply turning it on breaks the script. Any help or ideas would be appreciated 🙏

**Comment by ericcj** [comment]
even with the latest versions:

    typhoeus (1.4.0)
    ethon (0.12.0)
    ffi (1.13.1)

we also have this problem but only when running inside passenger, not on the console.  and it segfaults ruby because of https://github.com/typhoeus/typhoeus/issues/492

**Comment by sdhull** [comment]
FWIW @ericcj I _was_ having this issue while running a very simple script from console

**Comment by prem-prakash** [comment]
same problem here

**Comment by jpriollaud** [comment]
Maybe related, I'm seeing weird garbled characters in verbose mode:

`�TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
���ֶ:�$<�G�rs�ZT�oHEVf����!����u)UЗ��?f�yEAh?�kF7��u�`
