### ISSUE TITLE
Getting undefined method when running on ARM M1 with uptodate libffi

### ISSUE THREAD

**Issue by rist** [typhoeus/typhoeus#669]
After getting the most recent version of libffi I don't get any segmentation faults any more but this:

```
Traceback (most recent call last):
	19: from bug.rb:5:in `<main>'
	18: from /Users/iostest/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/actions.rb:22:in `get'
	17: from /Users/iostest/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
	16: from /Users/iostest/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
	15: from /Users/iostest/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
	14: from /Users/iostest/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
	13: from /Users/iostest/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16:in `run'
	12: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy/operations.rb:33:in `perform'
	11: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
	10: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
	 9: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
	 8: from /Users/iostest/.gem/gems/typhoeus-1.4.0/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
	 7: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy.rb:302:in `mirror'
	 6: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy/mirror.rb:14:in `from_easy'
	 5: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy/mirror.rb:14:in `each'
	 4: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/easy/mirror.rb:15:in `block in from_easy'
	 3: from (eval):1:in `total_time'
	 2: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/curls/infos.rb:144:in `get_info_double'
	 1: from /Users/iostest/.gem/gems/ethon-0.12.0/lib/ethon/curls/infos.rb:144:in `easy_getinfo'
/Users/iostest/.gem/gems/ffi-1.14.2/lib/ffi/enum.rb:157:in `to_native': undefined method `[]' for nil:NilClass (NoMethodError)
```

the content of my `bug.rb` is
```
require "typhoeus"
require 'netrc'
require 'yaml'

response =  Typhoeus.get('https://cdn.cocoapods.org/' + '/CocoaPods-version.yml', :netrc_file => Netrc.default_path, :netrc => :optional)
response_hash = YAML.load(response.body)

puts response_hash
```

I'm using bundle to execute that script - here are the relevant installed versions:

```iostest@S0M10 george-app-ios % bundle
Using netrc 0.11.0
Using ffi 1.14.2
Using ethon 0.12.0
Using typhoeus 1.4.0
…
Using safe_yaml 1.0.5
```

**Comment by felipedmesquita** [comment]
Hi everyone! Since we've had many similar issues with ffi, libcurl and arm macs at the time, most seem solved by using the current versions. To help us better triage current problems, I'm closing this and ask that you open a new issue if this is still a problem.
