### ISSUE TITLE
Ethon::Errors::InvalidOption - The option: path_as_is is invalid.

### ISSUE THREAD

**Issue by dprobinson** [typhoeus/typhoeus#678]
Trying to use `CURLOPT_PATH_AS_IS` via `:path_as_is` option results in the following error:

> Ethon::Errors::InvalidOption (The option: path_as_is is invalid.)

It's defined in Ethon here: https://github.com/typhoeus/ethon/blob/master/lib/ethon/curls/options.rb#L253

Version: typhoeus 1.4.0

Code to reproduce:
```ruby
require 'typhoeus'

Typhoeus::Request.new("https://github.com",  method: :get, path_as_is: true).run
```
Result:
```
Traceback (most recent call last):
       16: from /home/user/.rvm/rubies/ruby-2.7.1/bin/irb:23:in `<main>'
       15: from /home/user/.rvm/rubies/ruby-2.7.1/bin/irb:23:in `load'
       14: from /home/user/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
       13: from (irb):2
       12: from /home/user/.rvm/gems/ruby-2.7.1/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
       11: from /home/user/.rvm/gems/ruby-2.7.1/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
       10: from /home/user/.rvm/gems/ruby-2.7.1/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
        9: from /home/user/.rvm/gems/ruby-2.7.1/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
        8: from /home/user/.rvm/gems/ruby-2.7.1/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:15:in `run'
        7: from /home/user/.rvm/gems/ruby-2.7.1/gems/typhoeus-1.4.0/lib/typhoeus/easy_factory.rb:81:in `get'
        6: from /home/user/.rvm/gems/ruby-2.7.1/gems/ethon-0.12.0/lib/ethon/easy/http.rb:39:in `http_request'
        5: from /home/user/.rvm/gems/ruby-2.7.1/gems/ethon-0.12.0/lib/ethon/easy/http/get.rb:17:in `setup'
        4: from /home/user/.rvm/gems/ruby-2.7.1/gems/ethon-0.12.0/lib/ethon/easy/http/actionable.rb:99:in `setup'
        3: from /home/user/.rvm/gems/ruby-2.7.1/gems/ethon-0.12.0/lib/ethon/easy.rb:235:in `set_attributes'
        2: from /home/user/.rvm/gems/ruby-2.7.1/gems/ethon-0.12.0/lib/ethon/easy.rb:235:in `each_pair'
        1: from /home/user/.rvm/gems/ruby-2.7.1/gems/ethon-0.12.0/lib/ethon/easy.rb:238:in `block in set_attributes'
Ethon::Errors::InvalidOption (The option: path_as_is is invalid.)
```

**Comment by dprobinson** [comment]
Never mind, it appears to have been a bug upstream in Ethon, fixed in https://github.com/typhoeus/ethon/pull/171
