### ISSUE TITLE
Empty headers when on_headers callback is called

### ISSUE THREAD

**Issue by semaperepelitsa** [typhoeus/typhoeus#705]
The specs that were previously passing fine are now failing.

Pass: https://github.com/typhoeus/typhoeus/actions/runs/2773032378
Fail: https://github.com/semaperepelitsa/typhoeus/actions/runs/3471220663

```
2022-11-15T14:16:06.4946999Z Failures:
2022-11-15T14:16:06.4947344Z 
2022-11-15T14:16:06.4947657Z   1) Typhoeus::Request::Operations#run calls on_headers and on_body
2022-11-15T14:16:06.4948918Z      Failure/Error: request.on_complete { |response| expect(response).not_to be_nil ; expect(response.headers).to eq(headers) ; expect(response.body).to be_empty }
2022-11-15T14:16:06.4950433Z      
2022-11-15T14:16:06.4951072Z        expected: #<Typhoeus::Response::Header({})>
2022-11-15T14:16:06.4952106Z             got: #<Typhoeus::Response::Header({"Connection"=>"Keep-Alive", "Content-Length"=>"1039", "Content-Type"=>"...nt-Type-Options"=>"nosniff", "X-Frame-Options"=>"SAMEORIGIN", "X-Xss-Protection"=>"1; mode=block"})>
2022-11-15T14:16:06.4952782Z      
2022-11-15T14:16:06.4953180Z        (compared using ==)
2022-11-15T14:16:06.4953541Z      
2022-11-15T14:16:06.4953913Z        Diff:
2022-11-15T14:16:06.4954476Z        @@ -1,8 +1,15 @@
2022-11-15T14:16:06.4956354Z        -{}
2022-11-15T14:16:06.4956767Z        +{"Content-Type"=>"text/html;charset=utf-8",
2022-11-15T14:16:06.4957187Z        + "Content-Length"=>"1039",
2022-11-15T14:16:06.4957594Z        + "X-Xss-Protection"=>"1; mode=block",
2022-11-15T14:16:06.4958041Z        + "X-Content-Type-Options"=>"nosniff",
2022-11-15T14:16:06.4958482Z        + "X-Frame-Options"=>"SAMEORIGIN",
2022-11-15T14:16:06.4959092Z        + "Server"=>"WEBrick/1.7.0 (Ruby/3.1.2/2022-04-12)",
2022-11-15T14:16:06.4959626Z        + "Date"=>"Tue, 15 Nov 2022 14:16:05 GMT",
2022-11-15T14:16:06.4960027Z        + "Connection"=>"Keep-Alive"}
2022-11-15T14:16:06.4960333Z        
2022-11-15T14:16:06.4960879Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:102:in `block in <module:Support>'
2022-11-15T14:16:06.4961547Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:111:in `notify_failure'
2022-11-15T14:16:06.4962223Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
2022-11-15T14:16:06.4963334Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
2022-11-15T14:16:06.4964285Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
2022-11-15T14:16:06.4965021Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
2022-11-15T14:16:06.4965724Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
2022-11-15T14:16:06.4966427Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
2022-11-15T14:16:06.4967263Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/expectation_target.rb:101:in `to'
2022-11-15T14:16:06.4967899Z      # ./spec/typhoeus/request/operations_spec.rb:56:in `block (4 levels) in <top (required)>'
2022-11-15T14:16:06.4968456Z      # ./lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
2022-11-15T14:16:06.4968927Z      # ./lib/typhoeus/request/callbacks.rb:145:in `each'
2022-11-15T14:16:06.4971711Z      # ./lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
2022-11-15T14:16:06.4973139Z      # ./lib/typhoeus/request/operations.rb:35:in `finish'
2022-11-15T14:16:06.4975698Z      # ./lib/typhoeus/easy_factory.rb:170:in `block in set_callback'
2022-11-15T14:16:06.4978546Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `block in complete'
2022-11-15T14:16:06.4979119Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `each'
2022-11-15T14:16:06.4979654Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `complete'
2022-11-15T14:16:06.4980178Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:34:in `perform'
2022-11-15T14:16:06.4980615Z      # ./lib/typhoeus/request/operations.rb:16:in `run'
2022-11-15T14:16:06.4981014Z      # ./lib/typhoeus/request/cacheable.rb:18:in `run'
2022-11-15T14:16:06.4981406Z      # ./lib/typhoeus/request/block_connection.rb:31:in `run'
2022-11-15T14:16:06.4981801Z      # ./lib/typhoeus/request/stubbable.rb:25:in `run'
2022-11-15T14:16:06.4982179Z      # ./lib/typhoeus/request/before.rb:26:in `run'
2022-11-15T14:16:06.4982643Z      # ./spec/typhoeus/request/operations_spec.rb:57:in `block (3 levels) in <top (required)>'
2022-11-15T14:16:06.4983175Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `instance_exec'
2022-11-15T14:16:06.4983720Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `block in run'
2022-11-15T14:16:06.4984337Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
2022-11-15T14:16:06.4984973Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
2022-11-15T14:16:06.4985515Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
2022-11-15T14:16:06.4986084Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
2022-11-15T14:16:06.4986613Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
2022-11-15T14:16:06.4987173Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
2022-11-15T14:16:06.4987761Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
2022-11-15T14:16:06.4988312Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
2022-11-15T14:16:06.4989039Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
2022-11-15T14:16:06.4989604Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
2022-11-15T14:16:06.4990141Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
2022-11-15T14:16:06.4990683Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
2022-11-15T14:16:06.4991302Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
2022-11-15T14:16:06.4991824Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
2022-11-15T14:16:06.4992344Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
2022-11-15T14:16:06.4992904Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
2022-11-15T14:16:06.4993438Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
2022-11-15T14:16:06.4993980Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
2022-11-15T14:16:06.4994554Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
2022-11-15T14:16:06.4995118Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
2022-11-15T14:16:06.4995771Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
2022-11-15T14:16:06.4996336Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
2022-11-15T14:16:06.4997062Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
2022-11-15T14:16:06.4997664Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
2022-11-15T14:16:06.4998204Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
2022-11-15T14:16:06.4998756Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/exe/rspec:4:in `<main>'
2022-11-15T14:16:06.4999207Z 
2022-11-15T14:16:06.4999530Z   2) Typhoeus::Request::Operations#run calls on_headers and on_complete
2022-11-15T14:16:06.5000348Z      Failure/Error: request.on_complete { |response| expect(response).not_to be_nil ; expect(response.headers).to eq(headers) ; expect(response.body).not_to be_empty }
2022-11-15T14:16:06.5000805Z      
2022-11-15T14:16:06.5001301Z        expected: #<Typhoeus::Response::Header({})>
2022-11-15T14:16:06.5002164Z             got: #<Typhoeus::Response::Header({"Connection"=>"Keep-Alive", "Content-Length"=>"1039", "Content-Type"=>"...nt-Type-Options"=>"nosniff", "X-Frame-Options"=>"SAMEORIGIN", "X-Xss-Protection"=>"1; mode=block"})>
2022-11-15T14:16:06.5002757Z      
2022-11-15T14:16:06.5003069Z        (compared using ==)
2022-11-15T14:16:06.5003392Z      
2022-11-15T14:16:06.5003712Z        Diff:
2022-11-15T14:16:06.5004021Z        @@ -1,8 +1,15 @@
2022-11-15T14:16:06.5004398Z        -{}
2022-11-15T14:16:06.5004842Z        +{"Content-Type"=>"text/html;charset=utf-8",
2022-11-15T14:16:06.5005234Z        + "Content-Length"=>"1039",
2022-11-15T14:16:06.5005675Z        + "X-Xss-Protection"=>"1; mode=block",
2022-11-15T14:16:06.5006142Z        + "X-Content-Type-Options"=>"nosniff",
2022-11-15T14:16:06.5006590Z        + "X-Frame-Options"=>"SAMEORIGIN",
2022-11-15T14:16:06.5007171Z        + "Server"=>"WEBrick/1.7.0 (Ruby/3.1.2/2022-04-12)",
2022-11-15T14:16:06.5007626Z        + "Date"=>"Tue, 15 Nov 2022 14:16:05 GMT",
2022-11-15T14:16:06.5008053Z        + "Connection"=>"Keep-Alive"}
2022-11-15T14:16:06.5008389Z        
2022-11-15T14:16:06.5008964Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:102:in `block in <module:Support>'
2022-11-15T14:16:06.5009683Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:111:in `notify_failure'
2022-11-15T14:16:06.5010296Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
2022-11-15T14:16:06.5011006Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
2022-11-15T14:16:06.5011749Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
2022-11-15T14:16:06.5012453Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
2022-11-15T14:16:06.5013099Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
2022-11-15T14:16:06.5013794Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
2022-11-15T14:16:06.5014503Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.0/lib/rspec/expectations/expectation_target.rb:101:in `to'
2022-11-15T14:16:06.5015161Z      # ./spec/typhoeus/request/operations_spec.rb:63:in `block (4 levels) in <top (required)>'
2022-11-15T14:16:06.5015667Z      # ./lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
2022-11-15T14:16:06.5016167Z      # ./lib/typhoeus/request/callbacks.rb:145:in `each'
2022-11-15T14:16:06.5016679Z      # ./lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
2022-11-15T14:16:06.5017206Z      # ./lib/typhoeus/request/operations.rb:35:in `finish'
2022-11-15T14:16:06.5017654Z      # ./lib/typhoeus/easy_factory.rb:170:in `block in set_callback'
2022-11-15T14:16:06.5018243Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `block in complete'
2022-11-15T14:16:06.5018866Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `each'
2022-11-15T14:16:06.5019446Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `complete'
2022-11-15T14:16:06.5020073Z      # ./vendor/bundle/ruby/3.1.0/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:34:in `perform'
2022-11-15T14:16:06.5020578Z      # ./lib/typhoeus/request/operations.rb:16:in `run'
2022-11-15T14:16:06.5021053Z      # ./lib/typhoeus/request/cacheable.rb:18:in `run'
2022-11-15T14:16:06.5021479Z      # ./lib/typhoeus/request/block_connection.rb:31:in `run'
2022-11-15T14:16:06.5021948Z      # ./lib/typhoeus/request/stubbable.rb:25:in `run'
2022-11-15T14:16:06.5022430Z      # ./lib/typhoeus/request/before.rb:26:in `run'
2022-11-15T14:16:06.5022919Z      # ./spec/typhoeus/request/operations_spec.rb:64:in `block (3 levels) in <top (required)>'
2022-11-15T14:16:06.5023552Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `instance_exec'
2022-11-15T14:16:06.5024166Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `block in run'
2022-11-15T14:16:06.5024880Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
2022-11-15T14:16:06.5025608Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
2022-11-15T14:16:06.5026255Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
2022-11-15T14:16:06.5026890Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
2022-11-15T14:16:06.5027493Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
2022-11-15T14:16:06.5028171Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
2022-11-15T14:16:06.5028860Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
2022-11-15T14:16:06.5029500Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
2022-11-15T14:16:06.5050948Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
2022-11-15T14:16:06.5051532Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
2022-11-15T14:16:06.5052098Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
2022-11-15T14:16:06.5052648Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
2022-11-15T14:16:06.5053191Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
2022-11-15T14:16:06.5053734Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
2022-11-15T14:16:06.5054267Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
2022-11-15T14:16:06.5054836Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
2022-11-15T14:16:06.5055361Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
2022-11-15T14:16:06.5055919Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
2022-11-15T14:16:06.5056497Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
2022-11-15T14:16:06.5057063Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
2022-11-15T14:16:06.5057585Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
2022-11-15T14:16:06.5058122Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
2022-11-15T14:16:06.5058638Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
2022-11-15T14:16:06.5059143Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
2022-11-15T14:16:06.5059643Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
2022-11-15T14:16:06.5060120Z      # ./vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.0/exe/rspec:4:in `<main>'
2022-11-15T14:16:06.5061077Z 
2022-11-15T14:16:06.5061232Z Finished in 0.82241 seconds (files took 0.39947 seconds to load)
2022-11-15T14:16:06.5061606Z 457 examples, 2 failures, 1 pending
2022-11-15T14:16:06.5061752Z 
2022-11-15T14:16:06.5061842Z Failed examples:
2022-11-15T14:16:06.5061971Z 
2022-11-15T14:16:06.5062459Z rspec ./spec/typhoeus/request/operations_spec.rb:52 # Typhoeus::Request::Operations#run calls on_headers and on_body
2022-11-15T14:16:06.5063355Z rspec ./spec/typhoeus/request/operations_spec.rb:60 # Typhoeus::Request::Operations#run calls on_headers and on_complete
2022-11-15T14:16:06.5063629Z 
2022-11-15T14:16:06.5063729Z Randomized with seed 62239
```

**Comment by codealchemy** [comment]
This looks to be related to the most recent release of `ethon` (`0.16.0`, specifically, the header updates from https://github.com/typhoeus/ethon/pull/221)

**Comment by Kyrluckechuck** [comment]
Thanks for pointing to that, I went ahead and filed a bug report at https://github.com/typhoeus/ethon/issues/231 to hopefully get that addressed at the package source.

**Comment by felipedmesquita** [comment]
Thanks @semaperepelitsa, @codealchemy and @Kyrluckechuck for the detailed report. Should be fixed now by https://github.com/typhoeus/ethon/pull/264. Once I get an ethon release with the fix out we can require that version in the next release of typhoeus.
