### ISSUE TITLE
Test failures with ethon-0.16.0

### ISSUE THREAD

**Issue by thesamesam** [typhoeus/typhoeus#710]
Hi,

With ethon-0.16.0, I seem to get the following test failures:
```
>>> Test phase: dev-ruby/typhoeus-1.4.0-r1
 * Running test phase for ruby27

Randomized with seed 24949
......................................................................................................................................F..F............................................................................................................................................*...........................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Typhoeus::Request::Callbacks#execute_callbacks when local on_complete and gobal on_success runs all global callbacks first
     # No reason given
     # ./spec/typhoeus/request/callbacks_spec.rb:86


Failures:

  1) Typhoeus::Request::Operations#run calls on_headers and on_body
     Failure/Error: request.on_complete { |response| expect(response).not_to be_nil ; expect(response.headers).to eq(headers) ; expect(response.body).to be_empty }

       expected: #<Typhoeus::Response::Header({})>
            got: #<Typhoeus::Response::Header({"Connection"=>"Keep-Alive", "Content-Length"=>"1016", "Content-Type"=>"...nt-Type-Options"=>"nosniff", "X-Frame-Options"=>"SAMEORIGIN", "X-Xss-Protection"=>"1; mode=block"})>

       (compared using ==)

       Diff:
       @@ -1,8 +1,15 @@
       -{}
       +{"Content-Type"=>"text/html;charset=utf-8",
       + "Content-Length"=>"1016",
       + "X-Xss-Protection"=>"1; mode=block",
       + "X-Content-Type-Options"=>"nosniff",
       + "X-Frame-Options"=>"SAMEORIGIN",
       + "Server"=>"WEBrick/1.7.0 (Ruby/2.7.7/2022-11-24)",
       + "Date"=>"Sat, 24 Dec 2022 05:58:35 GMT",
       + "Connection"=>"Keep-Alive"}

     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:102:in `block in <module:Support>'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:111:in `notify_failure'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/typhoeus/request/operations_spec.rb:56:in `block (4 levels) in <top (required)>'
     # ./lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
     # ./lib/typhoeus/request/callbacks.rb:145:in `each'
     # ./lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
     # ./lib/typhoeus/request/operations.rb:35:in `finish'
     # ./lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `block in complete'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `each'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `complete'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:34:in `perform'
     # ./lib/typhoeus/request/operations.rb:16:in `run'
     # ./lib/typhoeus/request/cacheable.rb:18:in `run'
     # ./lib/typhoeus/request/block_connection.rb:31:in `run'
     # ./lib/typhoeus/request/stubbable.rb:25:in `run'
     # ./lib/typhoeus/request/before.rb:26:in `run'
     # ./spec/typhoeus/request/operations_spec.rb:57:in `block (3 levels) in <top (required)>'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `instance_exec'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `block in run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/bin/rspec:4:in `<top (required)>'
     # /usr/sbin/rspec-3:9:in `load'
     # /usr/sbin/rspec-3:9:in `<main>'

  2) Typhoeus::Request::Operations#run calls on_headers and on_complete
     Failure/Error: request.on_complete { |response| expect(response).not_to be_nil ; expect(response.headers).to eq(headers) ; expect(response.body).not_to be_empty }

       expected: #<Typhoeus::Response::Header({})>
            got: #<Typhoeus::Response::Header({"Connection"=>"Keep-Alive", "Content-Length"=>"1016", "Content-Type"=>"...nt-Type-Options"=>"nosniff", "X-Frame-Options"=>"SAMEORIGIN", "X-Xss-Protection"=>"1; mode=block"})>

       (compared using ==)

       Diff:
       @@ -1,8 +1,15 @@
       -{}
       +{"Content-Type"=>"text/html;charset=utf-8",
       + "Content-Length"=>"1016",
       + "X-Xss-Protection"=>"1; mode=block",
       + "X-Content-Type-Options"=>"nosniff",
       + "X-Frame-Options"=>"SAMEORIGIN",
       + "Server"=>"WEBrick/1.7.0 (Ruby/2.7.7/2022-11-24)",
       + "Date"=>"Sat, 24 Dec 2022 05:58:35 GMT",
       + "Connection"=>"Keep-Alive"}

     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:102:in `block in <module:Support>'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-support-3.12.0/lib/rspec/support.rb:111:in `notify_failure'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-expectations-3.12.1/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/typhoeus/request/operations_spec.rb:63:in `block (4 levels) in <top (required)>'
     # ./lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
     # ./lib/typhoeus/request/callbacks.rb:145:in `each'
     # ./lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
     # ./lib/typhoeus/request/operations.rb:35:in `finish'
     # ./lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `block in complete'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `each'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/response_callbacks.rb:74:in `complete'
     # /usr/lib64/ruby/gems/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:34:in `perform'
     # ./lib/typhoeus/request/operations.rb:16:in `run'
     # ./lib/typhoeus/request/cacheable.rb:18:in `run'
     # ./lib/typhoeus/request/block_connection.rb:31:in `run'
     # ./lib/typhoeus/request/stubbable.rb:25:in `run'
     # ./lib/typhoeus/request/before.rb:26:in `run'
     # ./spec/typhoeus/request/operations_spec.rb:64:in `block (3 levels) in <top (required)>'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `instance_exec'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `block in run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/lib64/ruby/gems/2.7.0/gems/rspec-core-3.12.0/bin/rspec:4:in `<top (required)>'
     # /usr/sbin/rspec-3:9:in `load'
     # /usr/sbin/rspec-3:9:in `<main>'

Finished in 0.62772 seconds (files took 0.35138 seconds to load)
450 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/typhoeus/request/operations_spec.rb:52 # Typhoeus::Request::Operations#run calls on_headers and on_body
rspec ./spec/typhoeus/request/operations_spec.rb:60 # Typhoeus::Request::Operations#run calls on_headers and on_complete

Randomized with seed 24949

 * ERROR: dev-ruby/typhoeus-1.4.0-r1::gentoo failed (test phase):
 *   rspec failed
```

The failures consistently go away if I downgrade to ethon-0.15.0. I looked at https://github.com/typhoeus/ethon/compare/v0.15.0...v0.16.0 but it wasn't obvious to me which change is responsible.

**Comment by dleidert** [comment]
That change caused this: <https://github.com/typhoeus/ethon/compare/v0.15.0...v0.16.0#diff-c84e8cd368b926848d91aed22b3e26bc6c9d3e7e0e651423b9a3cb7d51549ba4>

If I revert that change, the tests succeed again.

**Comment by dblock** [comment]
Ran into the same, bisected to a narrower change and opened https://github.com/typhoeus/ethon/issues/229.

**Comment by thesamesam** [comment]
Thank you!
