### ISSUE TITLE
tests fail with faraday 2 - faraday-typhoeus should be added as dependency in Gemfile

### ISSUE THREAD

**Issue by pravi** [typhoeus/typhoeus#717]
Currently the tests fail with 

```
An error occurred while loading ./spec/typhoeus/adapters/faraday_spec.rb.
Failure/Error: remove_method :call              if method_defined? :call

NameError:
  method `call' not defined in Faraday::Adapter::Typhoeus
# ./lib/typhoeus/adapters/faraday.rb:28:in `remove_method'
# ./lib/typhoeus/adapters/faraday.rb:28:in `<class:Typhoeus>'
# ./lib/typhoeus/adapters/faraday.rb:21:in `<class:Adapter>'
# ./lib/typhoeus/adapters/faraday.rb:4:in `<module:Faraday>'
# ./lib/typhoeus/adapters/faraday.rb:3:in `<top (required)>'
# 
```

**Comment by SahSantoshh** [comment]
Hi @pravi did you find any solution?

**Comment by courtneymiller2010** [comment]
It looks like using `faraday` v2 with this gem doesn't work. Instead, I switched to using [faraday-typhoeus](https://github.com/dleavitt/faraday-typhoeus) and this issue went away. I also had to switch out my requires from `require "typhoeus/adapters/faraday"` to `require "faraday/typhoeus"`
